In [1]:
#Regex 
#Import re moduel
import re
import numpy as np

In [2]:
text = "This is a good day"
if re.search("good",text):
    print("found")
else:
    print("Alas :(")

found


### Search looks for a pattern and returns a boolean
### re.search looks at any part of the text
### re.match looks at the begining of the text
### re.split("keyword",text) returns all the text after that keyword
### re.findall("keyword",text) returns all instances where that keyword is found

In [3]:
text = "Kannas is a good guy, Kannas is a Master in Wind Energy, Kanna is looking for a job."
re.split("Kannas",text) # Keyword is case sensitive

['',
 ' is a good guy, ',
 ' is a Master in Wind Energy, Kanna is looking for a job.']

In [4]:
re.findall("Kannas",text)

['Kannas', 'Kannas']

###  The regex specification standard defines a markup language to describe patterns in text. Let's start with anchors. Anchors specify the start and/or end of the string that you're trying to match. The caret character(^) means Start, and the dollar sign($) character means End. If you put caret before a string, it means that the texts that the regex processor retrieves must start with the string you specify. For ending, you have to put the dollar sign character after the string. It means that the texts regex retrieves must end with a string you specified.

In [5]:
re.match("^Kannas",text)

<re.Match object; span=(0, 6), match='Kannas'>

In [6]:
re.match("Kannas$",text)

# Patterns and Character Classes

In [7]:
#create a string of single learners grades over a semester in one course across all of their assignments.
#So grades equals, and I'll just put a string of As, Bs and Cs. No Ds for this student.
grades = "AAAAABABCCA"

In [8]:
re.findall("A",grades)

['A', 'A', 'A', 'A', 'A', 'A', 'A']

In [9]:
re.findall("[AB]",grades) #If we want to count the number of A's and B's in the list.

['A', 'A', 'A', 'A', 'A', 'B', 'A', 'B', 'A']

In [10]:
re.findall("[A][B-C]",grades) #This is set operator: You can also include a range of characters,alphanumerically 

['AB', 'AB']

In [11]:
re.findall("[B][A-C]",grades)

['BA', 'BC']

In [12]:
#pipe operator "|"
re.findall("[AB]|[BC]",grades)

['A', 'A', 'A', 'A', 'A', 'B', 'A', 'B', 'C', 'C', 'A']

In [13]:
re.findall("[^A]",grades) #Negation of results when we want only the grades which are not A's

['B', 'B', 'C', 'C']

# Quantifiers

### Quantifiers are the number of times you want to pattern to be matched in order to actually count as a match. The most basic quantifiers, the expression of E, e{m,n}, where E is the expression or character we're matching, M is the minimum number of times you want it to be matched, and N is the maximum number of times the item could be matched. 

In [14]:
re.findall("A{2,10}",grades)

['AAAAA']

In [15]:
re.findall("A{1,1}A{1,1}",grades)

['AA', 'AA']

In [16]:
re.findall("A{1,2}B{1,2}C{1,2}",grades)

['ABCC']

In [17]:
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [18]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

In [19]:
a_a = np.linspace(1,20,20)
b_b = np.linspace(21,40,20)


In [20]:
l2_dist(a_a.T, b_b.T)

89.44271909999159

In [21]:

l2_dist(a_a, b_b)

89.44271909999159

In [22]:
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [23]:
a4

array([1, 2, 3])

In [24]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
print(old)
new = old
new[0, :2] = 0

print(old)

[[1 1 1]
 [1 1 1]]
[[0 0 1]
 [1 1 1]]


In [25]:
r = np.linspace(0,35,36)
r = r.reshape(6,6)

r[2:4,2:4]

array([[14., 15.],
       [20., 21.]])

In [26]:
s = 'ACBCAC'
re.findall('^AC', s)

['AC']

In [27]:
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
print(result)
L = len(result)
print(L)

['A', 'AA', 'AA', 'AA', 'A']
5


In [28]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''
pattern = '\(.\)' 
print(len(re.findall(pattern,text)))

4


### Practice Regular Expressions for different functions

In [31]:
text = 'Who is an overseas (NRI) elector-Can an NRI settled in foreign land become an elector of electoral roll in India'
mm = re.search(r'(?<=-)\w+',text)
mm.group(0)

'Can'

In [39]:
ms = re.split(r'(?<=-)\W+',text)

In [63]:
# All fruits that start with vowel letters and end with non vowel letters
t1 = 'unicorn'
t2 = 'element'
t3 = 'banana'
t4 = 'apple'
mq1 = re.match("^[aeiou]\w*[^aeiou]$",t4) # '^' Start with character [aeiou] and \w any words and repetition but should not with [^aeiou]
print(mq1)

None


In [91]:
# Capture numbers in octal or hexadecimal representation in Python.
# Octal numbers start with a prefix "0o" (number zero followed by lowercase letter o),
# and are followed by one or more numbers in the range of 0 to 7. 
tq1 = "0o117"
tq2 = "0xf3"
tq3 = "0o12f"
mq2 = re.match("(0o+[0-7]+)|([0x]+[0-9a-f]+)",tq1) # '+' matches 0 followed by o but not repetition of 00
print(mq2)

<re.Match object; span=(0, 5), match='0o117'>


In [ ]:
# Capture a "Firstname Lastname" at the beginning of each line.
# Your regex should NOT capture the name in the sentence as it does not start from the beginning of the string.
# Notice that the name should consist of two words. 
# Each word should start with a capital letter and has zero or more lowercase letters followed.
# No other symbols are allowed in the name.
